version: '3.7'

services:
  cppromotionapi:
    environment:
      - DIGI_ENVIRONMENT=development
      - PRINCIPALCODE=ONES
      - ASPNETCORE_ENVIRONMENT=prod
      - ASPNETCORE_URLS=http://+:80
      - CACHEEXPIRES=99999
      - ECOGATEWAY=https://ones-api.vndigitech.com/v1/
      - CONNECTION=Server=14.161.18.75;Port=7332;Database=cprdos_system;User Id=cprdos;Password=P@ssw0rd2023
      - IS_DEPLOY=true
    ports:
      - "5340:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro