name: CICD To Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0
      with: 
         ssh-private-key: ${{ secrets.STA }}
         script: |
          ssh root@139.162.42.67 'cd /home/od/cicd && git pull'
      
     

