name: CICD To Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Set up Docker Compose
      # run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

      - name: Build and push Docker image
        run: |
          docker-compose -f docker-compose.yml build
          echo "$DOCKER_PASSWORD" | docker login -username "$DOCKER_USERNAME" --password
          docker-compose -f docker-compose.yml push

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
      #- name: Set up Docker Compose
      #  run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

      - name: Deploy with Docker Compose
        run: docker-compose -f docker-compose.yml up -d
      
     

