name: CICD To Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #- name: Set up Docker Compose
      #  run: sudo curl -L "https://github.com/docker/compose/releases/download/1.29.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

      - name: SSH into CentOS server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/od/cicd
            docker-compose up -d
      #- name: Build and push Docker image
      #  run: |
      #    docker-compose -f docker-compose.yml build
      #    echo "$DOCKER_PASSWORD" | docker login -username "$DOCKER_USERNAME" --password-stdin
      #    docker-compose -f docker-compose.yml push
      #  env:
      #    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

     

